version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  app:
    build: ./app
    ports:
      - "8080:8080"   # Flask Port
    environment:
      DB_HOST: db
      DB_NAME: flaskdb
      DB_USER: flaskuser
      DB_PASSWORD: flaskpass
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - appnet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

volumes:
  db_data:
  jenkins_home:

networks:
  appnet:
